# Generated by Django 3.2 on 2022-09-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('create_date',), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
