# Generated by Django 3.2 on 2022-09-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('counted_view', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('publish_data', models.DateField(null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('update_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
