# Generated by Django 3.2.15 on 2022-09-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post2',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post2',
            old_name='publish_data',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='post2',
            old_name='update_data',
            new_name='update_date',
        ),
    ]
