# Generated by Django 3.2 on 2022-09-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220926_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='image',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/'),
        ),
    ]
