# Generated by Django 3.2.15 on 2022-10-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_categorys_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post2',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
