# Generated by Django 3.2.15 on 2022-10-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.CharField(max_length=2),
        ),
    ]
