# Generated by Django 3.2.15 on 2022-10-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_test_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='sql_test',
        ),
    ]
