# Generated by Django 3.2.15 on 2022-10-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_test_sql_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='sql_test',
            name='age',
            field=models.IntegerField(default=None),
        ),
    ]
