# Generated by Django 3.2.15 on 2022-10-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_sql_test_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
